audiovisual/setup.py
burotel/setup.py
conversion/setup.py
cronjobs_cern/setup.py
custom_themes/setup.py
foundationsync/setup.py
livesync_cern/setup.py
outlook/setup.py
payment_cern/setup.py
ravem/setup.py
search_cern/setup.py

Kind of pointless without a version bump, but it's cleaner this way since the prerelease versions are a thing of the past 👴

Require Indico 2.0

---

cern_access/indico_cern_access/definition.py
cern_access/indico_cern_access/forms.py
cern_access/indico_cern_access/templates/cern_access_status.html
cern_access/indico_cern_access/util.py
cern_access/setup.py

Requests with no selected registration forms are confusing.
Also added a message box pointing to the docs once a request is sent/accepted.

CERNAccess: require at least one reg. form

---

cern_access/indico_cern_access/definition.py
cern_access/indico_cern_access/forms.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/templates/cern_access_status.html
cern_access/indico_cern_access/templates/event_request_details.html
cern_access/indico_cern_access/util.py
cern_access/setup.py

- allow sorting by state
- add icon in header (to make it clearer there's something to click)
- add option to request access by default (without requiring it)
```python
from sqlalchemy.orm.attributes import flag_modified
for req in Request.query.filter_by(type='cern-access'):
if 'regform_data_mode' not in req.data:
req.data['during_registration'] = False
req.data['during_registration_preselected'] = False
req.data['during_registration_required'] = False
else:
mode = req.data.pop('regform_data_mode')
req.data['during_registration'] = mode in (1, 2, 3)
req.data['during_registration_preselected'] = mode in (2, 3)
req.data['during_registration_required'] = mode == 2
flag_modified(req, 'data')
```

CERN access improvements

---

themes_cern/indico_themes_cern/templates/council.html
themes_cern/indico_themes_cern/themes-cern.yaml
themes_cern/indico_themes_cern/themes/council.scss

Some improvements in the "Council" theme:
* Show start time in "day header";
* Hide end time in entries;
* Make breaks look the same regardless of being nested or not;
I added a few core commits [in here](https://github.com/indico/indico/pull/3938/commits), to avoid opening yet another PR.

Council Theme - improvements

---

audiovisual/indico_audiovisual/definition.py
audiovisual/indico_audiovisual/plugin.py

This PR utilizes the changes made in https://github.com/indico/indico/pull/3938 to add a config option for the "Reply To:" address of notifications sent by the audiovisual plugin.

Audiovisual: set reply address for notifications

---

cern_access/indico_cern_access/templates/event_request_details.html

The link leads [here](https://indico-user-docs.web.cern.ch/indico-user-docs/cern/cern_access/#granting-access-to-participants).

CERNAccess: make warning text less ambiguous

---

burotel/indico_burotel/controllers.py
burotel/indico_burotel/plugin.py

related to indico/indico#4605
With the changes in there, the build in the plugin no longer produces separate react/sui bundles so we need to keep including the core ones.

Burotel: Use react/sui from webpack externals

---

themes_cern/indico_themes_cern/themes/council.scss

Allows margin overflows to fix the timetable time elements.

Themes CERN: Restore overflow in the timetable item wrapper

---

access_override/indico_access_override.py
access_override/setup.cfg
access_override/setup.py

There are some use cases where specific groups need non-standard read access to full category trees, and the previous approach of making these groups a manager of the root category had various disadvantages:
- full write access (since only management rights cascade all the way regardless of protection inheritance) even though they just need purely read-only access
- potentially huge search data updates when re-sending everything after an ACL change in a large category

Add Access Override plugin

---

burotel/pytest.ini
cern_access/pytest.ini
payment_cern/pytest.ini
ravem/pytest.ini

Celery is using an invalid legacy version specifier (celery/celery#7074)

Fix DeprecationWarning breaking tests

---

audiovisual/indico_audiovisual/definition.py
audiovisual/indico_audiovisual/forms.py
audiovisual/indico_audiovisual/util.py
audiovisual/setup.cfg

Especially for larger events, having to manually select all contributions is not only annoying, but error-prone, since additional contributions may be added at a later point and those would not be included by default with a manual selection.

Let managers override 'all contribs' room capability check

---

cronjobs_cern/indico_cronjobs_cern/plugin.py
cronjobs_cern/indico_cronjobs_cern/tasks.py
cronjobs_cern/setup.cfg

Instead of hardcoding a cern sender make the sending email configurable.

Make sender email configurable

---

audiovisual/indico_audiovisual/definition.py
audiovisual/indico_audiovisual/plugin.py
audiovisual/setup.cfg

Like this we can point it to a SNOW ticket email address so a new request creates a ticket. Behavior for emails on request withdrawal needs to be clarified with AV support; I don't think we can send a follow-up in the same ticket unless we record the message-ID, so the options are to either keep sending to the team address or opening yet another ticket in case of withdrawal.
depends on indico/indico#5501

Audiovisual: Send initial email from the user

---

conversion/indico_conversion/__init__.py
conversion/indico_conversion/blueprint.py
conversion/indico_conversion/cloudconvert.py
conversion/indico_conversion/conversion.py
conversion/indico_conversion/plugin.py
conversion/indico_conversion/templates/emails/cloudconvert_low_credits.html
conversion/indico_conversion/util.py
conversion/setup.cfg

Adds experimental CloudConvert support to the conversion plugin.
Feedback welcome!
- Make an account on CloudConvert and create an API key (you can also use the sandbox API which doesn't count towards the limit: https://cloudconvert.com/api/v2#overview, but then you can only upload limited files based on an md5 hash)
- Enable CloudConvert instead of Doconverter and set the API key in the Conversion plugin setttings.
- Make sure the webhook (`/conversion/cloudconvert/finished`) is reachable by cloudconvert (use ngrok for reverse proxy if needed)
- Upload a file with a supported extension (e.g. `docx`) and toggle `Convert to PDF`
- Wait & Pray

Add CloudConvert support

---

themes_cern/indico_themes_cern/themes/rucio.scss
themes_cern/setup.cfg

Make the RUCIO logo fit in the event header

---

foundationsync/indico_foundationsync/sync.py
foundationsync/setup.cfg

`oracledb` is the successor of `cx_Oracle` and besides being newer it has some advantages. For example, it supports "thin mode" which does not require `oracle-instantclient` to be installed on the system.

FoundationSync: Use oracledb instead of cx_Oracle

---

.github/workflows/ci.yml

Otherwise we can get problems when the setup job runs on a different patch release than the test/lint job because the symlink in the venv points to an exact x.y.z release

ci: Use exact Python version

---

cern_access/indico_cern_access/client/RegistrationIdentityDataForm.jsx

The default is 5 before and 5 after which is not very useful if the date picker is used to select a birth date.
This changes the range to 1904-2024.

CERNAccess: Use larger date range for the birth date field

---

i18n_demo/MANIFEST.in
i18n_demo/README.md
i18n_demo/indico_i18n_demo/blueprint.py
i18n_demo/indico_i18n_demo/controllers.py
i18n_demo/indico_i18n_demo/plugin.py
i18n_demo/indico_i18n_demo/templates/clone_button.html
i18n_demo/setup.cfg
i18n_demo/setup.py

This is a plugin intended for the [i18n demo instance](https://localization-demo.getindico.io). It does two things:
- All emails are redirected to the user who sent them (avoids spamming random people and lets you check email translations)
- Adds a new **Clone** button to the example events. When clicked, the corresponding event is cloned into your own personal subcategory and you get management rights to it. This way, you can see the management area without accidentally modifying the example events.

Add i18n-demo plugin

---

conversion/indico_conversion/conversion.py
conversion/indico_conversion/plugin.py
conversion/indico_conversion/util.py

As discussed in https://github.com/indico/indico/issues/6045 this adds the ability to request Google to return a pdf version of a google drive link (it requires an API key, and also the following [change](https://github.com/indico/indico/commit/8af9fe7655009c815b1b8ef485c2db48c2977c78) to indico)
cc @ThiefMaster

Add google drive conversion

---

i18n_demo/indico_i18n_demo/plugin.py

If there's no `session.user` we do not send the emails.
The exception is verification emails to allow people to create local accounts.

Do not send emails when the user is not logged in

---

outlook/indico_outlook/calendar.py

The deduplication logic was basically not deduplicating anything since it looked at the whole record, which included its ID... and with events that have 1k registrants and 10 update entries (per registrant) from individual changes made to the event's description, that's causing 10k instead of 1k updates being sent to the server...

Outlook: Do not send the same request multiple times

---

conversion/indico_conversion/conversion.py

Otherwise e.g. the LiveSync plugin does not pick up those new files, which breaks later queue runs that result in them being updated.

Conversion: Trigger after_process signal from tasks

---

payment_cern/indico_payment_cern/tests/util_test.py
payment_cern/indico_payment_cern/util.py

Postfinance requires that merchant reference only contains printable ascii characters.

Fix merchant reference to only contain printable ascii

---

zoom_rooms/indico_zoom_rooms/handlers.py

When moving a contribution from a block to another in an event that does not have any room set, it failed trying to read `None.room`.
```py
...
File "indico_zoom_rooms/handlers.py", line 150, in signal_link_object_updated
_check_link_object_for_updates(obj, changes)
File "indico_zoom_rooms/handlers.py", line 123, in _check_link_object_for_updates
_handle_contribution_move(
File "indico_zoom_rooms/handlers.py", line 81, in _handle_contribution_move
if (orig_zr_id := get_zoom_room_id(original_block.room if original_block else obj.event.room)) != (
File "indico_zoom_rooms/util.py", line 24, in get_zoom_room_id
room = obj if isinstance(obj, Room) else obj.room
AttributeError: 'NoneType' object has no attribute 'room'
```

ZoomRooms: Fix moving contrib with no room

---

outlook/indico_outlook/calendar.py
outlook/indico_outlook/migrations/20241117_1113_da9deaa182a4_update_user_setting.py
outlook/indico_outlook/plugin.py

Let the user configure if they want reminders or not, and how far in advance. Also let them define those as overrides per category.
@ThiefMaster note that this still needs some work, and I'm hoping you can give me a hint. My idea for the overrides is to have a single field where the user could define the status, reminder and/or reminder_time per category. However, I can't figure out how to get MultipleItemsField to have a validator so that _at least one of_ those values is filled in. Also, if the user doesn't specify a value for a particular variable, it should be passed as a None, otherwise  `_get_status`/`_get_reminder` can't tell the difference between an actual override and a blank. Perhaps this is too complicated for `MultipleItemsField` as it's currently implemented?

Allow custom reminders/times

---

ravem/indico_ravem/client/index.js

Kind of ugly because the state information is lost when you click disconnected and then don't force the disconnect, but I really did not want to touch more of this somewhat legacy JS code than necessary.

Ravem: Show correct name of connected VC

---

conversion/indico_conversion/conversion.py
conversion/indico_conversion/plugin.py

Convert all files with CloudConvert

---

cern_access/indico_cern_access/placeholders.py
cern_access/indico_cern_access/plugin.py

When automated ticket emails were disabled, it was not possible to share the access code to print a visitor badge on site via bulk emails sent to participants.

CERNAccess: Add email placeholder for access code

---

burotel/indico_burotel/cli.py

The CSV lib should be returning `str`, not bytes.

Burotel: remove wrong decode() call
