indico/indico-plugins-cern

cern_access/indico_cern_access/controllers.py
cern_access/indico_cern_access/placeholders.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/templates/_common.html
cern_access/indico_cern_access/templates/emails/identity_data_form_email.html
cern_access/indico_cern_access/templates/emails/ticket_email.html
cern_access/indico_cern_access/templates/identity_data_form.html
cern_access/indico_cern_access/util.py

Added official wording and mention of the date intervals.

Changes to sent e-mail

---

cern_access/indico_cern_access/controllers.py
cern_access/indico_cern_access/definition.py
cern_access/indico_cern_access/forms.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/templates/_common.html
cern_access/indico_cern_access/templates/cern_access_status.html
cern_access/indico_cern_access/templates/grant_access.html
cern_access/indico_cern_access/templates/identity_data_form.html
cern_access/indico_cern_access/templates/regform_identity_data_section.html
cern_access/indico_cern_access/util.py
cern_access/setup.py

CERNAccess: Request CERN access from a registration form

---

cern_access/indico_cern_access/controllers.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/templates/_common.html
cern_access/indico_cern_access/templates/emails/identity_data_form_email_default.html
cern_access/indico_cern_access/templates/grant_access.html
cern_access/indico_cern_access/templates/identity_data_form.html
cern_access/indico_cern_access/templates/identity_data_form_management.html
cern_access/indico_cern_access/util.py

CERNAccess: Consider ticket settings

---

custom_themes/indico_custom_themes/themes-cern.yaml
custom_themes/indico_custom_themes/themes/cern/print/administrative.scss
custom_themes/setup.py

Add  print stylesheet to administrative theme

---

audiovisual/indico_audiovisual/util.py
vc_assistance/MANIFEST.in
vc_assistance/indico_vc_assistance/__init__.py
vc_assistance/indico_vc_assistance/api.py
vc_assistance/indico_vc_assistance/blueprint.py
vc_assistance/indico_vc_assistance/client/style.scss
vc_assistance/indico_vc_assistance/controllers.py
vc_assistance/indico_vc_assistance/definition.py
vc_assistance/indico_vc_assistance/forms.py
vc_assistance/indico_vc_assistance/plugin.py
vc_assistance/indico_vc_assistance/templates/event_request_details.html
vc_assistance/indico_vc_assistance/templates/request_list.html
vc_assistance/indico_vc_assistance/templates/vc_assistance_request_link.html
vc_assistance/indico_vc_assistance/util.py
vc_assistance/indico_vc_assistance/views.py
vc_assistance/setup.py
vc_assistance/webpack-bundles.json

Closes https://github.com/indico/indico/issues/3622
ical endpoint: `https://indico.server.domain/export/vc-assistance.ics?alarms=<MIN_BEFORE>&apikey=<API_KEY>&signature=<SIGNATURE>`

VC Assistance plugin

---

outlook/indico_outlook/plugin.py

We are triggering a 'remove' operation when a registrant is deleted, but not when the whole form is.

Outlook: trigger remove when regform is deleted

---

cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/util.py
cern_access/setup.py

Participants were being set as active erroneously.

CERNAccess: Fix bug on user update

---

burotel/indico_burotel/client/js/components/DeskRenderer.jsx
burotel/indico_burotel/client/js/components/DeskRenderer.module.scss
burotel/indico_burotel/plugin.py

Closes indico/indico#3768
Related: https://github.com/indico/indico/pull/3816
In order to test run [this script](https://gist.github.com/mvidalgarcia/cfc6f4601c0bdfc487b7f968979525b6) in your `indico shell` (remember to set your Burotel DB)

Burotel: Long term property

---

burotel/indico_burotel/client/js/components/DeskInfoBoxes.jsx
burotel/indico_burotel/client/js/components/DeskInfoBoxes.module.scss
burotel/indico_burotel/client/js/components/RowLabel.jsx
burotel/indico_burotel/client/js/overrides.js

Related to: https://github.com/indico/indico/pull/3865
Closes indico/indico#3864

Burotel: Long term as timeline gutter + desk details

---

room_assistance/indico_room_assistance/client/style.scss
room_assistance/indico_room_assistance/controllers.py
room_assistance/indico_room_assistance/definition.py
room_assistance/indico_room_assistance/forms.py
room_assistance/indico_room_assistance/notifications.py
room_assistance/indico_room_assistance/plugin.py
room_assistance/indico_room_assistance/tasks.py
room_assistance/indico_room_assistance/templates/assistance_request_occurrences.html
room_assistance/indico_room_assistance/templates/auto_reject_no_overlapping_dates.txt
room_assistance/indico_room_assistance/templates/auto_reject_no_supported_room.txt
room_assistance/indico_room_assistance/templates/emails/creation_email_to_assistance.html
room_assistance/indico_room_assistance/templates/emails/modified_request_email_to_assistance.html
room_assistance/indico_room_assistance/templates/emails/room_assistance_emails.html
room_assistance/indico_room_assistance/templates/emails/withdrawn_email_to_assistance.html
room_assistance/indico_room_assistance/templates/request_list.html
room_assistance/indico_room_assistance/util.py
room_assistance/webpack-bundles.json

This is still a Draft since I need to just make sure that everything works fine. And apart from that I need to create proper commits with proper commit messages ;)
SQL command to update the request data:
```sql
UPDATE events.requests
SET data = data - 'start_dt' || json_build_object('occurrences', json_build_array(data->>'start_dt'))::JSONB
WHERE type = 'room-assistance' AND data ? 'start_dt';
```

Update the workflow of creating room assistance request

---

foundationsync/indico_foundationsync/plugin.py
foundationsync/indico_foundationsync/sync.py
foundationsync/setup.py

Non-synced fields (they are all moved to Indico):
* "Can be reserved"
* "Requires confirmation"
* Equipments
* Management e-group

FoundationSync: sync with AIS roles and remove equipment sync

---

foundationsync/indico_foundationsync/plugin.py
foundationsync/indico_foundationsync/sync.py

- Log what actually changed
- Do not log/count an "update" if nothing changed

Make foundationsync log more useful

---

vc_assistance/indico_vc_assistance/api.py
vc_assistance/indico_vc_assistance/plugin.py

A simple endpoint (`/export/room_vc_list/xxx/y-zz.json`) which exports all room bookings for a room in a given time span, as well as any associated events and VC rooms.

VC Assistance: add endpoint to export bookings

---

room_assistance/indico_room_assistance/templates/event_request_details.html
room_assistance/setup.py

Improve wording in room assistance plugin

---

burotel/indico_burotel/client/js/parametrized.jsx

Use react-overridable for parametrize

---

cern_access/indico_cern_access/plugin.py

Apply the changed included in https://github.com/indico/indico/pull/4426

Rename get_one(...) -> get_or_404(...)

---

burotel/indico_burotel/client/js/components/BootstrapOptions.jsx
burotel/indico_burotel/controllers.py
burotel/setup.py

Burotel: add HSE

---

ravem/indico_ravem/api.py
ravem/indico_ravem/client/index.js
ravem/indico_ravem/controllers.py
ravem/indico_ravem/operations.py
ravem/indico_ravem/plugin.py
ravem/indico_ravem/util.py
ravem/pytest.ini
ravem/required-build-plugins.json
ravem/setup.py
ravem/tests/conftest.py
ravem/tests/controllers_test.py
ravem/tests/operations/connect_test.py
ravem/tests/operations/disconnect_test.py
ravem/tests/operations_test.py
ravem/tests/util_test.py

Adds support to the zoom service
A great part of the changes made here were also related to the tests, which we do have a lot for this particular plugin.

Ravem: Update integration to support the zoom service

---

outlook/indico_outlook/calendar.py
outlook/setup.py

Related to https://github.com/indico/indico-plugins/pull/71 and https://github.com/indico/indico/pull/3840.

Outlook: post-process event metadata

---

audiovisual/indico_audiovisual/controllers.py
cronjobs_cern/indico_cronjobs_cern/tasks.py
room_assistance/indico_room_assistance/controllers.py
vc_assistance/indico_vc_assistance/controllers.py

Same as https://github.com/indico/indico/pull/4778.

Replace OrderedDict instances with dicts

---

foundationsync/indico_foundationsync/plugin.py
foundationsync/indico_foundationsync/sync.py
foundationsync/setup.py

The main source of truth for this is moving from Locations to Indico

FoundationSync: Do not synchronize/lock comments

---

audiovisual/indico_audiovisual/api.py
audiovisual/indico_audiovisual/blueprint.py
audiovisual/indico_audiovisual/controllers.py
audiovisual/indico_audiovisual/forms.py
vc_assistance/indico_vc_assistance/api.py
vc_assistance/indico_vc_assistance/blueprint.py
vc_assistance/indico_vc_assistance/controllers.py
vc_assistance/indico_vc_assistance/forms.py

Also fixes the ical category field which was incorrectly split into single chars before...
depends on indico/indico#5011

Use new signed links in VC/AV service overview ical feeds

---

access_override/indico_access_override.py
access_override/setup.cfg
audiovisual/indico_audiovisual/forms.py
audiovisual/indico_audiovisual/plugin.py
burotel/indico_burotel/plugin.py
burotel/setup.cfg
cern_access/indico_cern_access/plugin.py
cern_access/setup.cfg
conversion/indico_conversion/plugin.py
conversion/setup.cfg
outlook/indico_outlook/plugin.py
outlook/setup.cfg
payment_cern/indico_payment_cern/plugin.py
payment_cern/setup.cfg
ravem/indico_ravem/plugin.py
ravem/setup.cfg
room_assistance/indico_room_assistance/forms.py
room_assistance/setup.cfg
vc_assistance/indico_vc_assistance/forms.py
vc_assistance/indico_vc_assistance/plugin.py

Adapt to WTForms 3

---

cern_access/indico_cern_access/migrations/20210824_1204_e90cc0f72adc_add_adams_nonce_field.py
cern_access/indico_cern_access/models/access_requests.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/util.py
cern_access/tests/operations_test.py

Working fine on their test instance, but this should not be merged (or deployed) until they are ready to use this in prod.

CERNAccess: Adapt to new QR code format

---

access_override/setup.cfg
audiovisual/setup.cfg
burotel/setup.cfg
cern_access/setup.cfg
conversion/setup.cfg
cronjobs_cern/setup.cfg
foundationsync/setup.cfg
outlook/setup.cfg
payment_cern/setup.cfg
ravem/setup.cfg
room_assistance/setup.cfg
themes_cern/setup.cfg
themes_lcagenda/setup.cfg
vc_assistance/setup.cfg

Updated dependency to Python 3.10

Updated dependency to Python 3.10

---

cern_access/indico_cern_access/__init__.py
cern_access/indico_cern_access/migrations/20221103_1508_40e98cd40ab0_add_archive_table.py
cern_access/indico_cern_access/models/access_requests.py
cern_access/indico_cern_access/models/archived_requests.py
cern_access/indico_cern_access/plugin.py
cern_access/indico_cern_access/util.py
cern_access/setup.cfg
cern_access/tests/operations_test.py

fixes #120
depends on indico/indico#5559

CERNAccess: Archive requests when deleting registrations

---

outlook/indico_outlook/calendar.py
outlook/indico_outlook/plugin.py
outlook/indico_outlook/util.py
outlook/setup.cfg

Outlook: Adapt to new API

---

outlook/indico_outlook/calendar.py
outlook/indico_outlook/plugin.py
outlook/setup.cfg

Outlook: Allow overriding calendar status by category

---

burotel/indico_burotel/cli.py
burotel/setup.cfg

Geocoding was broken because of this.

Burotel: fix arguments in ArcGIS API call

---

burotel/indico_burotel/client/js/parametrized.jsx

This PR adds 'by weekday' specific UI overrides.

Burotel: Allow recurring weekday bookings

---

ravem/indico_ravem/api.py
ravem/indico_ravem/util.py
ruff.toml

Adapt to the ruff update in indico/indico#6168

Update ruff config

---

burotel/indico_burotel/client/js/parametrized.jsx

After https://github.com/indico/indico/pull/6155 this is no longer needed.

Remove reasonRequired override

---

i18n_demo/indico_i18n_demo/controllers.py
i18n_demo/indico_i18n_demo/plugin.py
i18n_demo/indico_i18n_demo/templates/clone_button.html

We need the user to be logged in to create a subcategory for them.
If a user is not logged in, the button is disabled with a tooltip telling them to log in.

[i18n-demo] Disable cloning when user not logged in

---

cern_access/indico_cern_access/util.py
cern_access/pyproject.toml
cronjobs_cern/indico_cronjobs_cern/tasks.py
cronjobs_cern/pyproject.toml
room_assistance/indico_room_assistance/notifications.py
room_assistance/indico_room_assistance/tasks.py
room_assistance/pyproject.toml

Adapt to make_email API change in Indico core

---

cern_access/indico_cern_access/client/RegistrationIdentityDataForm.jsx
cern_access/indico_cern_access/client/RegistrationIdentityDataForm.module.scss
cern_access/indico_cern_access/forms.py
cern_access/indico_cern_access/templates/regform_list_widget.html

This might depend on some changes in the date picker made in https://github.com/indico/indico/pull/6832, not sure. Just in case I'll wait with merging this until after that PR is also merged.

CERNAccess: Use new date picker

---

.github/workflows/ci.yml

Also use uv in all CI jobs where we still used classic pip
Merge indico/indico-gh-actions#1 first!

ci: Use astral-sh/setup-uv to install uv

---

outlook/indico_outlook/plugin.py
outlook/indico_outlook/util.py

another pick of "simple" functionality from #184

Outlook: Support adding favorite events
